### ISSUE TITLE
Reviews of the SIV mode lib

### ISSUE THREAD

**Issue by vdzhuvinov** [cryptomator/siv-mode#1]
Hi Sebastian,

Have there been any independent reviews of the SIV mode lib?

I consider using it in a OpenID Connect SDK for generating reversible pairwise user IDs
(http://www.javadoc.io/doc/com.nimbusds/oauth2-oidc-sdk/5.14)

Thanks,

Vladimir

**Comment by overheadhunter** [comment]
Hi Vladimir,

nope, no reviews I know of so far. But with merely 300 lines of code this should be rather fast process. 😄

**Comment by vdzhuvinov** [comment]
Good. I'm trying to get an expert to review the code before I link to it. I'll keep you informed. Thanks for making it available!
