### ISSUE TITLE
Dev Feature Request: Allow for providing a JCE provider in JceAesBlockCipher

### ISSUE THREAD

**Issue by patrickfav** [cryptomator/siv-mode#10]
A developer may implement her own adaption of block cipher with `BlockCipherFactory` but if she only wants to change the used security provider with the default AES impl this is quiet cumbersome as the BC dependencies have to be satisfied to copy the impl.

I propose to let `JceAesBlockCipher` and `SivMode` accept a `Provider` argument.

PR follows.

**Comment by overheadhunter** [comment]
You can already specifiy any provider via the `security.provider` setting in the security configuration file, but having the ability to define the Provider programmatically doesn't hurt.

Thanks for your PR!
