### ISSUE TITLE
Migrate to JUnit 5

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/siv-mode#12]
Make the tests run on Java 8 and use JUnit 5, especially to make use of [parameterized tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests).

**Comment by patrickfav** [comment]
Fyi there is also the parameterized test feature in JUnit 4: https://github.com/junit-team/junit4/wiki/Parameterized-tests

**Comment by overheadhunter** [comment]
> Fyi there is also the parameterized test feature in JUnit 4: https://github.com/junit-team/junit4/wiki/Parameterized-tests

I know, but it doesn't integrate well with IDEs, can't be combined with hierarchical tests (due to the fact that JUnit 4 only allows a single test runner at a time) and there are some other benefits in JUnit 5 (e.g. thanks to lambdas, testing exceptions is no longer such a pain in the ***).

We have already migrated most other libraries and it would be nice to have a common standard.
