### ISSUE TITLE
Add documentation on how to build the project

### ISSUE THREAD

**Issue by patrickfav** [cryptomator/siv-mode#13]
Even with the travis.yml, adding the profile and servers to the maven settings I didn't get to fully run the project through maven (i.e. `mvn clean install`) - I'd suggest adding a paragraph to your readme explaining what needs to be done to build the project.

**Comment by overheadhunter** [comment]
> I didn't get to fully run the project through maven (i.e. `mvn clean install`)

🤔 Why not? That _should_ be sufficient to build the project.

**Comment by patrickfav** [comment]
No, the issue seems to be that you use a compiler option set through the compiler plugin which is only supported on Java 9+: the release flag


			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
					<release>7</release>
					<encoding>UTF-8</encoding>
					<showWarnings>true</showWarnings>
				</configuration>
			</plugin>

Removing it let it build on JDK 8. See also: https://stackoverflow.com/questions/49105941/intellij-maven-project-fatal-error-compiling-invalid-flag-release. If you want require a specific JDK version, I recommend using the enforcer plugin: https://maven.apache.org/enforcer/enforcer-rules/requireJavaVersion.html 
 (and the maven version, since you use maven 3.6 features) otherwise it is a bit hard to debug.

Stack trace for reference:

```
[INFO] Compiling 3 source files to C:\Users\PatrickF\workspaces\siv-mode\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.843 s
[INFO] Finished at: 2019-05-04T00:04:39+02:00
[INFO] Final Memory: 11M/368M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project siv-mode: Fatal error compiling: invalid flag: --release -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project siv-mode: Fatal error compiling
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
...
Caused by: java.lang.IllegalArgumentException: invalid flag: --release
        at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:206)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:156)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:107)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:64)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
        ... 25 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

---

Nevertheless a couple of sentences how to build would be nice e.g.:

```

## Build

JDK 9+ and Maven 3.6 is required to build this project.

### Build with Maven

Use the Maven to create a jar including all dependencies

    mvnw clean install
```

**Comment by overheadhunter** [comment]
Ah I see, yes we need to update the pom.xml, maybe there is even a better way to cope with the multi-release-jar to make this a named module and stay compatible with Java 7 at the same time.

**Comment by patrickfav** [comment]
> Btw posting the error message instead of "it doesn't work" is usually a good idea.

I never asked you to fix my problem, I just recommended to add a section to your readme stating what steps are necessary to build your project (something I still think would make sense), as there are things which have to be set up specifically (i.e. having Java 9+).

**Comment by overheadhunter** [comment]
Still it would have spared me to think something is wrong with the build. I could have told you immediately that we're using JDK 9 features during build time.

And yes, documenting the requirements _does_ still make sense.
