### ISSUE TITLE
S2V operation

### ISSUE THREAD

**Issue by iT0ny** [cryptomator/siv-mode#14]
I'm writing my own implementation of Cryptomator based on [Architecture - Cryptomator](https://docs.cryptomator.org/en/latest/security/architecture/) and I've noticed that there's a difference in S2V operation in your code and the reference specification provided by [RFC 5297](https://tools.ietf.org/html/rfc5297#section-2.4) 

Is there a specific reason why you ignore a case when n is equal to zero
```
if n = 0 then
    return V = AES-CMAC(K, <one>)
fi
```

Thanks

**Comment by overheadhunter** [comment]
You might be right, it seems to be missing. I'll have to take a closer look. Wondering why there is not test vector in the RFC for n=0.

**Comment by iT0ny** [comment]
Thanks for the quick response, my main concern is, that fixing this will cause problems with internal file structure(e.g. root directory encrypted name will differ)

**Comment by overheadhunter** [comment]
> my main concern is, that fixing this will cause problems with internal file tree structure(e.g. root directory encrypted name will differ)

I will not affect file names (even in the root dir, the empty string will be passed as AD to SIV), but it would affect the mapping between directory IDs and directory names.

However, neither the iOS app (which uses an independent implementation) nor our test cases (more than 60k tests) report any difference. Note that the [test cases](https://github.com/cryptomator/siv-mode/blob/develop/src/test/go/siv-test-vectors.go) are generated using [this library](/jacobsa/crypto).

Also, the linked section 2.4 or RFC 5297 doesn't mention n = 0 being special (other than in the pseudocode).

**Comment by overheadhunter** [comment]
Ok I found it!

What the RFC calls `Sn` is in our case `plaintext`. Therefore n is _always_ greater than 0.

s2v is only used by encrypt and decrypt. In both cases plaintext will be passed to s2v.

Strictly speaking, s2v isn't implemented correctly, but we would just add dead code. I'll add a comment instead.

**Comment by iT0ny** [comment]
> Therefore n is _always_ greater than 0.

_Is it?_ 
When you create a vault you need to get encrypted root directory ID, which is 0 bytes, making n = 0. That’s why I specifically mentioned root directory being “broken”. For example, when performing `aesSiv(dirId, null, encryptionMasterKey, macMasterKey)`, where:

encryptionMasterKey = `379F554D FFC3FDB7 BC02C792 969B5B3A 300CE6C0 865D0914 CEBD7BCD C02F58D4`
macMasterKey = `24B9FD29 793D7070 2570AC49 FD4B06D3 DD35FED8 D535A97D CC5AFFB0 D015CC3D`
dirId = `empty data` (root directory ID is a special case and is empty, according to the documentation)

My implementation, if I ignore `n == 0` case, would give 
`SQG3NEP3MYX5XUAGQ633E5HLOI7CFOMO`

The result matches with your implementation because Cryptomator recognises that vault and is able to work with it w/o a problem.
Obviously, if I uncomment a part that handles `n == 0`, the output would be
`XGTUM3VSORABP4VFX4LPTYJ7PKCZDYZ3`

So if someone like me decides to make his own implementation using the documentation, it won't be compatible(basically the implementation won't work) with Cryptomator app, that you provide

**Comment by iT0ny** [comment]
I think not being able to reproduce functionality described in the documentation by using only technical specification is a big problem. Basically that means your app does not behave like it supposed to, so to speak.

**Comment by overheadhunter** [comment]
The length of the input values doesn't affect the number of input values. Even if the root dir id is an empty string, it is still passed to s2v.

**Comment by overheadhunter** [comment]
It is technically impossible for n to be 0, as plaintext is parameter that is used as `Sn`. I don't know what language you're using, but in Java it is impossible for this parameter to "stop existing".

**Comment by iT0ny** [comment]
> The length of the input values doesn't affect the number of input values.

Yeah, I misunderstood your comment about Sn being a plaintext. I somehow assumed, that n would correspond to a length of Sn, not the input with associated data 🤦‍♂️

Thanks again for your response.
